name: Build Project

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Git
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Install .NET 8.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      
      - name: Build TechnitiumLibrary.Net
        working-directory: ./TechnitiumLibrary
        run: dotnet build ./TechnitiumLibrary.Net -c Release
      
      - name: Build DnsServerCore.ApplicationCommon
        working-directory: ./DnsServer
        run: dotnet build ./DnsServerCore.ApplicationCommon
      
      - name: Restore dependencies
        working-directory: ./QueryLogsAMQP
        run: dotnet restore

      - name: Build QueryLogsAMQP
        working-directory: ./QueryLogsAMQP
        run: dotnet build --no-restore -c Release /p:Platform="Any CPU"

      - name: Add Licenses
        working-directory: "./QueryLogsAMQP/bin/Any CPU/Release"
        #if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          wget -O RabbitMQ.Client.LICENSE "https://raw.githubusercontent.com/rabbitmq/rabbitmq-dotnet-client/main/LICENSE-APACHE2"
          wget -O Newtonsoft.Json.LICENSE "https://raw.githubusercontent.com/JamesNK/Newtonsoft.Json/master/LICENSE.md"
          cp ../../../../LICENSE ./LICENSE
      
      - name: Make ZIP archive
        working-directory: "./QueryLogsAMQP/bin/Any CPU/Release"
        #if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          zip -r QueryLogsAMQP.zip ./
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          name: QueryLogsAMQP-Nightly.zip
          path: "./QueryLogsAMQP/bin/Any CPU/Release/QueryLogsAMQP.zip"
          if-no-files-found: error
          retention-days: 90
